import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettierConfig from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettierConfig,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".next/standalone/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build artifacts generated by OpenNext / Wrangler:
    ".open-next/**",
    ".wrangler/**",
  ]),
]);

export default eslintConfig;
