"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "fruits-drill"
compatibility_date = "2026-04-18"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
