"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "fruits-drill"
compatibility_date = "2026-04-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = false
upload_source_maps = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.traces]
enabled = true
destinations = ["grafana-traces"]

[observability.logs]
enabled = true
destinations = ["grafana-logs"]

[[d1_databases]]
binding = "DB"
database_name = "fruits-drill"
database_id = "c7d639b8-0931-4eeb-935e-68fda6f9426c"

[[r2_buckets]]
binding = "DRILL_FILES"
bucket_name = "fruits-drill"
preview_bucket_name = "fruits-drill-preview"

[env.preview]
workers_dev = true
preview_urls = true

[env.preview.assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "fruits-drill"
database_id = "c7d639b8-0931-4eeb-935e-68fda6f9426c"

[[env.preview.r2_buckets]]
binding = "DRILL_FILES"
bucket_name = "fruits-drill"
preview_bucket_name = "fruits-drill-preview"
